name: Fetch NSE Option Chain with Playwright

on:
  schedule:
    - cron: "*/6 * * * *"  # Every 6 minutes
  workflow_dispatch:

jobs:
  fetch-nse-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run Playwright Script
      run: |
        import asyncio
        from playwright.async_api import async_playwright
        import json, datetime

        async def run():
            now = datetime.datetime.utcnow().strftime("%Y-%m-%d_%H-%M")
            filename = f"option_chain_{now}.json"
            async with async_playwright() as p:
                browser = await p.chromium.launch()
                context = await browser.new_context()
                page = await context.new_page()
                await page.goto("https://www.nseindia.com")
                await page.wait_for_timeout(3000)  # Wait for cookies to set
                await page.goto("https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY")
                content = await page.content()

                try:
                    # Page content is HTML, extract JSON using evaluate
                    json_text = await page.evaluate("() => document.body.innerText")
                    data = json.loads(json_text)
                    with open(filename, "w") as f:
                        json.dump(data, f, indent=2)
                    print(f"Saved to {filename}")
                except Exception as e:
                    print("Error parsing response:", e)

                await browser.close()

        asyncio.run(run())
      shell: python

    - name: Commit and Push if file exists
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        FILE=$(ls option_chain_*.json 2>/dev/null || true)

        if [ -n "$FILE" ]; then
          git add $FILE
          git commit -m "Fetched NSE option chain at $(date)" || echo "No changes to commit"
          git push
        else
          echo "No file created, skipping commit."
