name: Fetch NSE Option Chain

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  fetch-nse-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Fetch NSE Data and Save
      run: |
        import requests, json, datetime, os

        symbol = 'NIFTY'
        headers = {
            "User-Agent": "Mozilla/5.0",
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://www.nseindia.com"
        }

        session = requests.Session()
        session.headers.update(headers)
        try:
            session.get("https://www.nseindia.com", timeout=10)
            url = f"https://www.nseindia.com/api/option-chain-indices?symbol={symbol}"
            response = session.get(url, timeout=10)
            
            if response.status_code == 200:
                data = response.json()
                now = datetime.datetime.utcnow().strftime("%Y-%m-%d_%H-%M")
                filename = f"option_chain_{now}.json"
                with open(filename, "w") as f:
                    json.dump(data, f, indent=2)
                print(f"Saved to {filename}")
            else:
                print("❌ Failed to fetch data, status code:", response.status_code)
        except Exception as e:
            print("⚠️ Exception occurred:", e)
      shell: python

    - name: Commit and Push if file exists
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        FILE=$(ls option_chain_*.json 2>/dev/null || true)

        if [ -n "$FILE" ]; then
          git add $FILE
          git commit -m "Fetched NSE option chain at $(date)" || echo "No changes to commit"
          git push
        else
          echo "❗ No file created, skipping commit."
        fi
