name: Download from Example.com

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 2 minutes
  workflow_dispatch:       # Allow manual trigger too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install requests
      run: pip install requests

    - name: Run Python script to download example.com
      run: |
        import requests
        r = requests.get("https://example.com")
        with open("example.html", "w", encoding="utf-8") as f:
            f.write(r.text)
      shell: python

    - name: Commit and Push
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        git add example.html
        git commit -m "Fetched example.com at $(date)" || echo "No changes to commit"
        git push origin HEAD:main
