name: Fetch NSE Option Chain

on:
  schedule:
    - cron: "*/6 * * * *"  # Every 6 minutes
  workflow_dispatch:

jobs:
  fetch-nse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: |
          import requests, json, datetime

          symbol = "NIFTY"
          headers = {
              "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
              "Accept-Language": "en-US,en;q=0.9",
              "Referer": "https://www.nseindia.com"
          }

          session = requests.Session()
          session.headers.update(headers)
          session.get("https://www.nseindia.com", timeout=10)

          url = f"https://www.nseindia.com/api/option-chain-indices?symbol={symbol}"
          res = session.get(url, timeout=10)

          if res.status_code == 200:
              data = res.json()
              now = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M")
              filename = f"option_chain_{now}.json"
              with open(filename, "w") as f:
                  json.dump(data, f)
              print(f"Saved {filename}")
          else:
              print("Failed to fetch data")

        shell: python

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if ls option_chain_*.json 1> /dev/null 2>&1; then
            git add option_chain_*.json
            git commit -m "Saved option chain at $(date)" || echo "No changes"
            git push
          else
            echo "No JSON file found to commit."
