name: Download NSE Option Chain

on:
  schedule:
     - cron: '*/5 * * * *'  # 10:00 AM IST every day (UTC time)
  workflow_dispatch:      # Optional manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the NSE Downloader
        run: python download_nse_data.py

      - name: Commit CSV file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.csv
          git commit -m "Added NSE data on $(date)" || echo "No changes to commit"
          git push
