name: Fetch NSE play

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install --with-deps firefox

    - name: Run NSE Fetcher
      run: |
        python download_nse_data.py || echo "Python script failed"

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        if compgen -G "option_chain_*.json" > /dev/null; then
          git add option_chain_*.json
          git commit -m "Fetched NSE Option Chain at $(date)" || echo "No changes to commit"
          git push
        else
          echo "No files to commit"
