name: Fetch NSE play

on:
  schedule:
    - cron: "0 */5 * * *"  # Every 5 hours
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install --with-deps firefox

    - name: Run NSE Fetcher
      run: python download_nse_chain.py

    - name: Process option chain JSONs
      run: python process_json.py

    - name: Sort processed fund data
      run: python fund_sort.py

    - name: Email results
      run: python send_email.py

