name: Fetch NSE play

on:
  schedule:
    - cron: "0 */9 * * *"  # Every 5 hours
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install --with-deps chromium

    - name: Run NSE Fetcher
      run: python mobile_tracker.py

    - name: send email
      run: python emmail.py
